import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Carousel } from '@/components/main/Carousel'

export default function Home() {
    return (
        <div className={styles.main}>
            <Head>
                <title>Music</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Carousel />
        </div>
    )
}
